# Generated by Django 5.1.7 on 2025-03-23 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='pickup_location',
            new_name='donor_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
