# Generated by Django 5.1.7 on 2025-03-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=20),
        ),
    ]
