# Generated by Django 5.1.7 on 2025-03-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_recipient_remove_donation_donor_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'permissions': [('can_claim_donations', 'Can claim donations')]},
        ),
    ]
