# Generated by Django 5.1.7 on 2025-04-02 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_alter_donation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('monthly_growth', models.FloatField(default=0.0)),
                ('people_helped', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='donation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='is_claimed',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='request',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='request',
            name='recipient',
        ),
        migrations.AddField(
            model_name='donation',
            name='donated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='food_needed',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='quantity_requested',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='request',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='request',
            name='requester_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=20),
        ),
    ]
