# Generated by Django 5.1.7 on 2025-04-05 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_alter_donation_options_remove_donation_donated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='recipient',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
