# Generated by Django 5.1.7 on 2025-04-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_donation_is_ready_donation_status_recipient_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_ready',
        ),
        migrations.AlterField(
            model_name='donation',
            name='food_item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('picked_up', 'Picked Up'), ('completed', 'Completed')], default='ready', max_length=20),
        ),
    ]
