# Generated by Django 5.1.7 on 2025-04-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_remove_donation_is_ready_alter_donation_food_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.recipient'),
        ),
    ]
