# Generated by Django 5.1.7 on 2025-04-05 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_deliverypartner_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='recipient',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='vehicle_type',
            field=models.CharField(default='Bike', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to='donations.deliverypartner'),
        ),
        migrations.AddField(
            model_name='donation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='food_item',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
