# Generated by Django 5.1.7 on 2025-04-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0020_donor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
