# Generated by Django 5.1.7 on 2025-04-06 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0021_donation_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='rating',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='donations.donation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.recipient')),
            ],
        ),
    ]
