# Generated by Django 5.1.7 on 2025-04-07 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0022_remove_donation_rating_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
