# Generated by Django 5.1.7 on 2025-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0024_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='phone',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='receiver',
            old_name='name',
            new_name='organization_name',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='address',
        ),
        migrations.AddField(
            model_name='receiver',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='organization_type',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
