# Generated by Django 5.1.7 on 2025-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0026_alter_donation_donor_alter_donor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_type',
            field=models.CharField(default='individual', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Hotel', 'Hotel'), ('Bakery', 'Bakery'), ('Individual', 'Individual')], default='individual', max_length=50),
            preserve_default=False,
        ),
    ]
