# Generated by Django 5.1.7 on 2025-04-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0027_donation_donor_type_donor_donor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
