# Generated by Django 5.1.7 on 2025-04-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0028_alter_donor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
