# Generated by Django 5.1.7 on 2025-04-19 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0029_donor_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='password',
        ),
        migrations.AddField(
            model_name='receiver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='organization_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='organization_type',
            field=models.CharField(max_length=255),
        ),
    ]
