# Generated by Django 5.1.7 on 2025-04-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0030_remove_receiver_password_receiver_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='food_item',
            field=models.CharField(max_length=100),
        ),
    ]
