# Generated by Django 5.1.7 on 2025-04-19 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0034_shelter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='contact_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='shelter',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
