# Generated by Django 5.1.7 on 2025-04-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0035_shelter_contact_number_shelter_number_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='number_of_people',
            field=models.IntegerField(),
        ),
    ]
