# Generated by Django 5.1.7 on 2025-04-20 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0039_deliverypartner_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='delivery_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.deliverypartner'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.donation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='shelter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donations.shelter'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
