# Generated by Django 5.1.7 on 2025-04-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0041_donation_is_active_alter_notification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
